[[redirects]]
from = "/"
to = "/home"
status = 301
force = false
query = {path = ":path"}
#conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
from = "/home"
to = "/home"
status = 200
force = true # COMMENT: ensure that we always redirect
