[[redirects]]
from = "/"
to = "/home"
status = 301
force = false
query = {path = ":path"}
#conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
from = "/home"
to = "/"
status = 200
force = true # COMMENT: ensure that we always redirect

[[redirects]]
from = "/login"
to = "https://hotel-project-team.netlify.app/login"
status = 200
force = true # COMMENT: ensure that we always redirect
